export const  FETCH_DATA_COME = 'FETCH_DATA_COME'
export const  FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
export const PAGINATE_DATA = 'PAGINATE_DATA';